# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

Perform Image Enhancement using opencv
aim ->to perform image enhancement using opencv
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow
image1=cv2.imread('image.jpg')
image =cv2.resize(image1, (0, 0), fx=0.1, fy=0.1, interpolation=cv2.INTER_AREA)

if image is None:
    print("No image found")
else:
    #Increase Brightness & Contrast
    bright=cv2.convertScaleAbs(image,alpha=1.2,beta=50)
    # 2. Equalize Histogram (Requires Grayscale)
    gray_img=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
    equalized_img=cv2.equalizeHist(gray_img)

    # 3. Sharpening Kernel
    kernel=np.array([[0,-1,0],
                       [-1,5,-1],
                       [0,-1,0]])

    # ddepth=-1 keeps the output image the same depth as input
    sharpened=cv2.filter2D(src=image,ddepth=-2,kernel=kernel)

    # Display Images
    cv2_imshow(image)
    cv2_imshow(bright)
    cv2_imshow(equalized_img)
    cv2_imshow(sharpened)

    cv2.waitKey(0)
    cv2.destroyAllWindows()

